# Generated by Django 5.0.6 on 2024-06-12 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about_artist', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='category/')),
                ('add_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('Art_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('aboutArt', models.TextField()),
                ('place', models.CharField(default='hi', max_length=20)),
                ('Artwork_year', models.BigIntegerField(default=0)),
                ('url', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='arts/')),
                ('price', models.IntegerField(default=10)),
                ('type', models.CharField(default='', max_length=100)),
                ('ArtistName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.arts')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_address', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.arts')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='artapp.order')),
            ],
        ),
    ]
