# Generated by Django 5.0.6 on 2024-06-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
